//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NqhBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NqhKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NqhKhoa()
        {
            this.nqhSinhVien = new HashSet<nqhSinhVien>();
        }
    
        public string NqhMaKH { get; set; }
        public string NqhTenKH { get; set; }
        public Nullable<bool> NqhTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nqhSinhVien> nqhSinhVien { get; set; }
    }
}
