//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NqhBaiKiemTraGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NqhK22CNT4Lesson07PREntities : DbContext
    {
        public NqhK22CNT4Lesson07PREntities()
            : base("name=NqhK22CNT4Lesson07PREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NqhKhoa> NqhKhoa { get; set; }
        public virtual DbSet<nqhSinhVien> nqhSinhVien { get; set; }
    }
}
