//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NqhK22CNTLesson11.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NqhK22CNTLesson11Entities : DbContext
    {
        public NqhK22CNTLesson11Entities()
            : base("name=NqhK22CNTLesson11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NqhCategory> NqhCategories { get; set; }
        public virtual DbSet<NqhProduct> NqhProducts { get; set; }
    }
}
