//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NqhK22CNTLesson11.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class NqhCategory
    {
       
        public int NqhID { get; set; }
        public string NqhCateName { get; set; }
        public Nullable<bool> NqhStatus { get; set; }
    }
}
