//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NqhK22CNTLesson11.Controllers
{
    using DocumentFormat.OpenXml.Wordprocessing;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NqhCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NqhCategory()
        {
            this.NqhProduct = new HashSet<NqhProduct>();
        }

        [Display(Name ="Mã danh mục")]  
        public int NqhID { get; set; }

        [Display(Name = "Tên danh mục")]
        public string NqhCateName { get; set; }

        [Display(Name = "Trạng thái")]    
        public Nullable<bool> NqhStatus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NqhProduct> NqhProduct {get; set; }
}
}
