//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NqhK22CNTLesson11.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class NqhProduct
    {
        public string NqhId2210900105 { get; set; }
        public string NqhProName { get; set; }
        public Nullable<int> NqhQty { get; set; }
        public Nullable<double> NqhPrice { get; set; }
        public Nullable<int> NqhCateId { get; set; }
        public Nullable<bool> NqhActive { get; set; }
    }
}
