//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NqhLesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NqhAccount
    {
        public int NqhID { get; set; }
        public string NqhUserName { get; set; }
        public string NqhPassWord { get; set; }
        public string NqhFullName { get; set; }
        public string NqhEmail { get; set; }
        public string NqhPhone { get; set; }
        public Nullable<bool> NqhActive { get; set; }
    }
}
